name: CI Cache Priming

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: prime-cache-b1c461d
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-b1c461d

      - name: Echo cache hit/miss result
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found — skipping install"
          fi
